server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: user-greetings-service

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 5
        sleepWindowInMilliseconds: 5000

greetings-service:
  ribbon:
    eureka:
      enabled: true
